services:
  minecraft:
    image: lastsandwich/minecraft-vellum-linux
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "29132:19132/udp"
      - "29132:19132/tcp"
    #restart: always
    # allow attaching to container
    tty: true
    stdin_open: true
    volumes:
      - C:\Minecraft\Vellum-Docker:/bds
